kazanac_site:
    resource: "@KazanacSiteBundle/Controller/"
    type:     annotation
    prefix:   /



kazanac_membre:
    resource: "@KazanacMembreBundle/Controller/"
    type:     annotation
    prefix:   /admin

#Route fosuserBundle

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"